export default function sitemap() {
    return [
      {
        url: 'https://www.emykozmetika.hu/',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'yearly',
        priority: 1.00,
      },
      {
        url: 'https://www.emykozmetika.hu/rolam',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/arak',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/galeria',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/kapcsolat',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/idopont-foglalas',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/o2lift-spa-voros-szonyeg-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-ormedic-lift',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-signature-facelift',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-lightening-lift-borvilagosito-hamlasztas',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-lightening-lift-forte-intenzive-borvilagosito-hamlasztas',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-wrinkle-lift-hamlaszto-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-wrinkle-lift-forte-intenziv-hamlaszto-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-acne-lift-aknes-bor-kezelese',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-beta-lift-aknekezelo-hamlasztas',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-perfection-lift-bormegujito-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-peel-perfection-lift-forte-intenziv-bormegujito-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/be-clear-tisztito-arckezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/illuminating-pigmenfolt-halvanyito-arckezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/the-max-ossejtes-arckezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/the-max-contour-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/image-glitz-and-glow-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/image-probiotikus-tisztito-arckezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/mikrobiome-borbarrier-erosito-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/basic-nyari-glow-radiance-refresh-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-mask-lapmaszk-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/tu-nelkuli-mezoterapia',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/geno-led-alacsony-intenzitasu-led-feny',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/sqt-bio-mikrotus-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/genosys-snowcell',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/mikrodermabrazio-gyemantfejes-technologia',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek/1-need-pro-mikrotus-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/deep-shoot-skin-booster',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/plazma-g-collage-frakcionalt-radiofrekvencias-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/aramo-bordiagnosztika-boranalizis-konzultacio',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/secret-rf',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/pollogen-oxygeneo',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/exosome-sejtterapia',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/hollywood-carbon-peeling',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.80,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/slow-aging-kezelesek',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/ferfi-kozmetika',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/esztetikai-sminktetovalas',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/wax-szortelenites',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/dokumentumok/adatkezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.64,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/secret-booster',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.51,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/1-need-pro',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.51,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/prekozmetikai-kezelesek/ejal-40-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.51,
      },
      {
        url: 'https://www.emykozmetika.hu/szolgaltatasok/image-skincare-protokolok/i-mask-hidratalo-lapmaszk-kezeles',
        lastModified: new Date('2025-03-31T08:41:26+00:00'),
        changeFrequency: 'monthly',
        priority: 0.51,
      },
    ];
  }